name: Trigger Jenkins

on:
  workflow_dispatch  # Manual trigger

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins
        run: |
          CRUMB=$(curl -s --user "$JENKINS_USER:$JENKINS_TOKEN" \
            "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")

          curl -X POST "$JENKINS_URL/job/jenkinsdeclarativetwo/buildWithParameters" \
            --user "$JENKINS_USER:$JENKINS_TOKEN" \
            -H "$CRUMB"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
