name : Trigger jenkins
on:
  workflow_dispatch
#Above is for triggering manaully not automatically

jobs:
  trigger:
    # This is for running this steps in the ubantu mode in github and jenkins
    runs-on: ubuntu-latest
    #steps are name and "|" to allow multiple commands
    steps:
      - name: Trigger jenkins
        run: |
          curl -X POST "$JENKINS_URL/job/jenkinsdeclarativejtwo/build" \
               --user "$JENKINS_USER:$JENKINS_TOKEN"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}

  
